

default:
	bash run_test.sh 65xx
	bash run_test.sh 680x0
	bash run_test.sh arm
	bash run_test.sh avr8
	bash run_test.sh dspic
	bash run_test.sh epiphany
	#bash run_test.sh mips32
	bash run_test.sh msp430
	bash run_test.sh msp430x
	bash run_test.sh pic32
	bash run_test.sh ps2_ee
	bash run_test.sh stm8
	bash run_test.sh z80

rebuild:
	sh build_arm.sh
	sh build_avr8.sh
	sh build_dspic.sh
	sh build_msp430.sh
	sh build_msp430x.sh


