

default:
	sh run_test.sh arm
	sh run_test.sh avr8
	sh run_test.sh dspic
	sh run_test.sh msp430
	sh run_test.sh msp430x

rebuild:
	sh build_arm.sh
	sh build_avr8.sh
	sh build_dspic.sh
	sh build_msp430.sh
	sh build_msp430x.sh


