#!/usr/bin/env python

print ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"
print ";;"
print ";; ESP32 registers"
print ";; Part of the naken_asm assembler"
print ";;"
print ";; Generated by: Michael Kohn (mike@mikekohn.net)"
print ";;               http://www.mikekohn.net/"
print ";;         Date: 2019-Feb-09"
print ";;"
print ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;"
print

registers = { }

fp = open("esp32.txt", "r")

for line in fp:
  line = line.strip()
  if not line: continue
  if line.startswith(";"): continue

  tokens = line.split()
  name = tokens[0]
  address = tokens[-2]
  mode = tokens[-1]

  registers[address] = [ name, mode ]

fp.close()

keys = registers.keys()
keys.sort()

for register in keys:
  data = registers[register]
  print data[0] + " equ " + register.lower()


