/**
 *  naken_asm assembler.
 *  Author: Michael Kohn
 *   Email: mike@mikekohn.net
 *     Web: https://www.mikekohn.net/
 * License: GPLv3
 *
 * Copyright 2010-2022 by Michael Kohn
 *
 */

#include <stdio.h>
#include <stdlib.h>
#include "table/8051.h"

struct _table_8051 table_8051[] =
{
  { "nop",   { OP_NONE,       OP_NONE,      OP_NONE    }, -1 }, // 0x00
  { "ajmp",  { OP_PAGE,       OP_NONE,      OP_NONE    },  0 }, // 0x01
  { "ljmp",  { OP_CODE_ADDR,  OP_NONE,      OP_NONE    }, -1 }, // 0x02
  { "rr",    { OP_A,          OP_NONE,      OP_NONE    }, -1 }, // 0x03
  { "inc",   { OP_A,          OP_NONE,      OP_NONE    }, -1 }, // 0x04
  { "inc",   { OP_IRAM_ADDR,  OP_NONE,      OP_NONE    }, -1 }, // 0x05
  { "inc",   { OP_AT_REG,     OP_NONE,      OP_NONE    },  0 }, // 0x06
  { "inc",   { OP_AT_REG,     OP_NONE,      OP_NONE    },  1 }, // 0x07
  { "inc",   { OP_REG,        OP_NONE,      OP_NONE    },  0 }, // 0x08
  { "inc",   { OP_REG,        OP_NONE,      OP_NONE    },  1 }, // 0x09
  { "inc",   { OP_REG,        OP_NONE,      OP_NONE    },  2 }, // 0x0a
  { "inc",   { OP_REG,        OP_NONE,      OP_NONE    },  3 }, // 0x0b
  { "inc",   { OP_REG,        OP_NONE,      OP_NONE    },  4 }, // 0x0c
  { "inc",   { OP_REG,        OP_NONE,      OP_NONE    },  5 }, // 0x0d
  { "inc",   { OP_REG,        OP_NONE,      OP_NONE    },  6 }, // 0x0e
  { "inc",   { OP_REG,        OP_NONE,      OP_NONE    },  7 }, // 0x0f
  { "jbc",   { OP_BIT_ADDR,   OP_RELADDR,   OP_NONE    }, -1 }, // 0x10
  { "acall", { OP_PAGE,       OP_NONE,      OP_NONE    },  0 }, // 0x11
  { "lcall", { OP_CODE_ADDR,  OP_NONE,      OP_NONE    }, -1 }, // 0x12
  { "rrc",   { OP_A,          OP_NONE,      OP_NONE    }, -1 }, // 0x13
  { "dec",   { OP_A,          OP_NONE,      OP_NONE    }, -1 }, // 0x14
  { "dec",   { OP_IRAM_ADDR,  OP_NONE,      OP_NONE    }, -1 }, // 0x15
  { "dec",   { OP_AT_REG,     OP_NONE,      OP_NONE    },  0 }, // 0x16
  { "dec",   { OP_AT_REG,     OP_NONE,      OP_NONE    },  1 }, // 0x17
  { "dec",   { OP_REG,        OP_NONE,      OP_NONE    },  0 }, // 0x18
  { "dec",   { OP_REG,        OP_NONE,      OP_NONE    },  1 }, // 0x19
  { "dec",   { OP_REG,        OP_NONE,      OP_NONE    },  2 }, // 0x1a
  { "dec",   { OP_REG,        OP_NONE,      OP_NONE    },  3 }, // 0x1b
  { "dec",   { OP_REG,        OP_NONE,      OP_NONE    },  4 }, // 0x1c
  { "dec",   { OP_REG,        OP_NONE,      OP_NONE    },  5 }, // 0x1d
  { "dec",   { OP_REG,        OP_NONE,      OP_NONE    },  6 }, // 0x1e
  { "dec",   { OP_REG,        OP_NONE,      OP_NONE    },  7 }, // 0x1f
  { "jb",    { OP_BIT_ADDR,   OP_RELADDR,   OP_NONE    }, -1 }, // 0x20
  { "ajmp",  { OP_PAGE,       OP_NONE,      OP_NONE    },  1 }, // 0x21
  { "ret",   { OP_NONE,       OP_NONE,      OP_NONE    }, -1 }, // 0x22
  { "rl",    { OP_A,          OP_NONE,      OP_NONE    }, -1 }, // 0x23
  { "add",   { OP_A,          OP_DATA,      OP_NONE    }, -1 }, // 0x24
  { "add",   { OP_A,          OP_IRAM_ADDR, OP_NONE    }, -1 }, // 0x25
  { "add",   { OP_A,          OP_AT_REG,    OP_NONE    },  0 }, // 0x26
  { "add",   { OP_A,          OP_AT_REG,    OP_NONE    },  1 }, // 0x27
  { "add",   { OP_A,          OP_REG,       OP_NONE    },  0 }, // 0x28
  { "add",   { OP_A,          OP_REG,       OP_NONE    },  1 }, // 0x29
  { "add",   { OP_A,          OP_REG,       OP_NONE    },  2 }, // 0x2a
  { "add",   { OP_A,          OP_REG,       OP_NONE    },  3 }, // 0x2b
  { "add",   { OP_A,          OP_REG,       OP_NONE    },  4 }, // 0x2c
  { "add",   { OP_A,          OP_REG,       OP_NONE    },  5 }, // 0x2d
  { "add",   { OP_A,          OP_REG,       OP_NONE    },  6 }, // 0x2e
  { "add",   { OP_A,          OP_REG,       OP_NONE    },  7 }, // 0x2f
  { "jnb",   { OP_BIT_ADDR,   OP_RELADDR,   OP_NONE    }, -1 }, // 0x30
  { "acall", { OP_PAGE,       OP_NONE,      OP_NONE    },  1 }, // 0x31
  { "reti",  { OP_NONE,       OP_NONE,      OP_NONE    }, -1 }, // 0x32
  { "rlc",   { OP_A,          OP_NONE,      OP_NONE    }, -1 }, // 0x33
  { "addc",  { OP_A,          OP_DATA,      OP_NONE    }, -1 }, // 0x34
  { "addc",  { OP_A,          OP_IRAM_ADDR, OP_NONE    }, -1 }, // 0x35
  { "addc",  { OP_A,          OP_AT_REG,    OP_NONE    },  0 }, // 0x36
  { "addc",  { OP_A,          OP_AT_REG,    OP_NONE    },  1 }, // 0x37
  { "addc",  { OP_A,          OP_REG,       OP_NONE    },  0 }, // 0x38
  { "addc",  { OP_A,          OP_REG,       OP_NONE    },  1 }, // 0x39
  { "addc",  { OP_A,          OP_REG,       OP_NONE    },  2 }, // 0x3a
  { "addc",  { OP_A,          OP_REG,       OP_NONE    },  3 }, // 0x3b
  { "addc",  { OP_A,          OP_REG,       OP_NONE    },  4 }, // 0x3c
  { "addc",  { OP_A,          OP_REG,       OP_NONE    },  5 }, // 0x3d
  { "addc",  { OP_A,          OP_REG,       OP_NONE    },  6 }, // 0x3e
  { "addc",  { OP_A,          OP_REG,       OP_NONE    },  7 }, // 0x3f
  { "jc",    { OP_RELADDR,    OP_NONE,      OP_NONE    }, -1 }, // 0x40
  { "ajmp",  { OP_PAGE,       OP_NONE,      OP_NONE    },  2 }, // 0x41
  { "orl",   { OP_IRAM_ADDR,  OP_A,         OP_NONE    }, -1 }, // 0x42
  { "orl",   { OP_IRAM_ADDR,  OP_DATA,      OP_NONE    }, -1 }, // 0x43
  { "orl",   { OP_A,          OP_DATA,      OP_NONE    }, -1 }, // 0x44
  { "orl",   { OP_A,          OP_IRAM_ADDR, OP_NONE    }, -1 }, // 0x45
  { "orl",   { OP_A,          OP_AT_REG,    OP_NONE    },  0 }, // 0x46
  { "orl",   { OP_A,          OP_AT_REG,    OP_NONE    },  1 }, // 0x47
  { "orl",   { OP_A,          OP_REG,       OP_NONE    },  0 }, // 0x48
  { "orl",   { OP_A,          OP_REG,       OP_NONE    },  1 }, // 0x49
  { "orl",   { OP_A,          OP_REG,       OP_NONE    },  2 }, // 0x4a
  { "orl",   { OP_A,          OP_REG,       OP_NONE    },  3 }, // 0x4b
  { "orl",   { OP_A,          OP_REG,       OP_NONE    },  4 }, // 0x4c
  { "orl",   { OP_A,          OP_REG,       OP_NONE    },  5 }, // 0x4d
  { "orl",   { OP_A,          OP_REG,       OP_NONE    },  6 }, // 0x4e
  { "orl",   { OP_A,          OP_REG,       OP_NONE    },  7 }, // 0x4f
  { "jnc",   { OP_RELADDR,    OP_NONE,      OP_NONE    }, -1 }, // 0x50
  { "acall", { OP_PAGE,       OP_NONE,      OP_NONE    },  2 }, // 0x51
  { "anl",   { OP_IRAM_ADDR,  OP_A,         OP_NONE    }, -1 }, // 0x52
  { "anl",   { OP_IRAM_ADDR,  OP_DATA,      OP_NONE    }, -1 }, // 0x53
  { "anl",   { OP_A,          OP_DATA,      OP_NONE    }, -1 }, // 0x54
  { "anl",   { OP_A,          OP_IRAM_ADDR, OP_NONE    }, -1 }, // 0x55
  { "anl",   { OP_A,          OP_AT_REG,    OP_NONE    },  0 }, // 0x56
  { "anl",   { OP_A,          OP_AT_REG,    OP_NONE    },  1 }, // 0x57
  { "anl",   { OP_A,          OP_REG,       OP_NONE    },  0 }, // 0x58
  { "anl",   { OP_A,          OP_REG,       OP_NONE    },  1 }, // 0x59
  { "anl",   { OP_A,          OP_REG,       OP_NONE    },  2 }, // 0x5a
  { "anl",   { OP_A,          OP_REG,       OP_NONE    },  3 }, // 0x5b
  { "anl",   { OP_A,          OP_REG,       OP_NONE    },  4 }, // 0x5c
  { "anl",   { OP_A,          OP_REG,       OP_NONE    },  5 }, // 0x5d
  { "anl",   { OP_A,          OP_REG,       OP_NONE    },  6 }, // 0x5e
  { "anl",   { OP_A,          OP_REG,       OP_NONE    },  7 }, // 0x5f
  { "jz",    { OP_RELADDR,    OP_NONE,      OP_NONE    }, -1 }, // 0x60
  { "ajmp",  { OP_PAGE,       OP_NONE,      OP_NONE    },  3 }, // 0x61
  { "xrl",   { OP_IRAM_ADDR,  OP_A,         OP_NONE    }, -1 }, // 0x62
  { "xrl",   { OP_IRAM_ADDR,  OP_DATA,      OP_NONE    }, -1 }, // 0x63
  { "xrl",   { OP_A,          OP_DATA,      OP_NONE    }, -1 }, // 0x64
  { "xrl",   { OP_A,          OP_IRAM_ADDR, OP_NONE    }, -1 }, // 0x65
  { "xrl",   { OP_A,          OP_AT_REG,    OP_NONE    },  0 }, // 0x66
  { "xrl",   { OP_A,          OP_AT_REG,    OP_NONE    },  1 }, // 0x67
  { "xrl",   { OP_A,          OP_REG,       OP_NONE    },  0 }, // 0x68
  { "xrl",   { OP_A,          OP_REG,       OP_NONE    },  1 }, // 0x69
  { "xrl",   { OP_A,          OP_REG,       OP_NONE    },  2 }, // 0x6a
  { "xrl",   { OP_A,          OP_REG,       OP_NONE    },  3 }, // 0x6b
  { "xrl",   { OP_A,          OP_REG,       OP_NONE    },  4 }, // 0x6c
  { "xrl",   { OP_A,          OP_REG,       OP_NONE    },  5 }, // 0x6d
  { "xrl",   { OP_A,          OP_REG,       OP_NONE    },  6 }, // 0x6e
  { "xrl",   { OP_A,          OP_REG,       OP_NONE    },  7 }, // 0x6f
  { "jnz",   { OP_RELADDR,    OP_NONE,      OP_NONE    }, -1 }, // 0x70
  { "acall", { OP_PAGE,       OP_NONE,      OP_NONE    },  3 }, // 0x71
  { "orl",   { OP_C,          OP_BIT_ADDR,  OP_NONE    }, -1 }, // 0x72
  { "jmp",   { OP_AT_A_PLUS_DPTR, OP_NONE,  OP_NONE    }, -1 }, // 0x73
  { "mov",   { OP_A,          OP_DATA,      OP_NONE    }, -1 }, // 0x74
  { "mov",   { OP_IRAM_ADDR,  OP_DATA,      OP_NONE    }, -1 }, // 0x75
  { "mov",   { OP_AT_REG,     OP_DATA,      OP_NONE    },  0 }, // 0x76
  { "mov",   { OP_AT_REG,     OP_DATA,      OP_NONE    },  1 }, // 0x77
  { "mov",   { OP_REG,        OP_DATA,      OP_NONE    },  0 }, // 0x78
  { "mov",   { OP_REG,        OP_DATA,      OP_NONE    },  1 }, // 0x79
  { "mov",   { OP_REG,        OP_DATA,      OP_NONE    },  2 }, // 0x7a
  { "mov",   { OP_REG,        OP_DATA,      OP_NONE    },  3 }, // 0x7b
  { "mov",   { OP_REG,        OP_DATA,      OP_NONE    },  4 }, // 0x7c
  { "mov",   { OP_REG,        OP_DATA,      OP_NONE    },  5 }, // 0x7d
  { "mov",   { OP_REG,        OP_DATA,      OP_NONE    },  6 }, // 0x7e
  { "mov",   { OP_REG,        OP_DATA,      OP_NONE    },  7 }, // 0x7f
  { "sjmp",  { OP_RELADDR,    OP_NONE,      OP_NONE    }, -1 }, // 0x80
  { "ajmp",  { OP_PAGE,       OP_NONE,      OP_NONE    },  4 }, // 0x81
  { "anl",   { OP_C,          OP_BIT_ADDR,  OP_NONE    }, -1 }, // 0x82
  { "movc",  { OP_A,       OP_AT_A_PLUS_PC, OP_NONE    }, -1 }, // 0x83
  { "div",   { OP_AB,         OP_NONE,      OP_NONE    }, -1 }, // 0x84
  { "mov",   { OP_IRAM_ADDR,  OP_IRAM_ADDR, OP_NONE    }, -1 }, // 0x85
  { "mov",   { OP_IRAM_ADDR,  OP_AT_REG,    OP_NONE    },  0 }, // 0x86
  { "mov",   { OP_IRAM_ADDR,  OP_AT_REG,    OP_NONE    },  1 }, // 0x87
  { "mov",   { OP_IRAM_ADDR,  OP_REG,       OP_NONE    },  0 }, // 0x88
  { "mov",   { OP_IRAM_ADDR,  OP_REG,       OP_NONE    },  1 }, // 0x89
  { "mov",   { OP_IRAM_ADDR,  OP_REG,       OP_NONE    },  2 }, // 0x8a
  { "mov",   { OP_IRAM_ADDR,  OP_REG,       OP_NONE    },  3 }, // 0x8b
  { "mov",   { OP_IRAM_ADDR,  OP_REG,       OP_NONE    },  4 }, // 0x8c
  { "mov",   { OP_IRAM_ADDR,  OP_REG,       OP_NONE    },  5 }, // 0x8d
  { "mov",   { OP_IRAM_ADDR,  OP_REG,       OP_NONE    },  6 }, // 0x8e
  { "mov",   { OP_IRAM_ADDR,  OP_REG,       OP_NONE    },  7 }, // 0x8f
  { "mov",   { OP_DPTR,       OP_DATA_16,   OP_NONE    }, -1 }, // 0x90
  { "acall", { OP_PAGE,       OP_NONE,      OP_NONE    },  4 }, // 0x91
  { "mov",   { OP_BIT_ADDR,   OP_C,         OP_NONE    }, -1 }, // 0x92
  { "movc",  { OP_A,     OP_AT_A_PLUS_DPTR, OP_NONE    }, -1 }, // 0x93
  { "subb",  { OP_A,          OP_DATA,      OP_NONE    }, -1 }, // 0x94
  { "subb",  { OP_A,          OP_IRAM_ADDR, OP_NONE    }, -1 }, // 0x95
  { "subb",  { OP_A,          OP_AT_REG,    OP_NONE    },  0 }, // 0x96
  { "subb",  { OP_A,          OP_AT_REG,    OP_NONE    },  1 }, // 0x97
  { "subb",  { OP_A,          OP_REG,       OP_NONE    },  0 }, // 0x98
  { "subb",  { OP_A,          OP_REG,       OP_NONE    },  1 }, // 0x99
  { "subb",  { OP_A,          OP_REG,       OP_NONE    },  2 }, // 0x9A
  { "subb",  { OP_A,          OP_REG,       OP_NONE    },  3 }, // 0x9b
  { "subb",  { OP_A,          OP_REG,       OP_NONE    },  4 }, // 0x9c
  { "subb",  { OP_A,          OP_REG,       OP_NONE    },  5 }, // 0x9d
  { "subb",  { OP_A,          OP_REG,       OP_NONE    },  6 }, // 0x9e
  { "subb",  { OP_A,          OP_REG,       OP_NONE    },  7 }, // 0x9f
  { "orl",   { OP_C,     OP_SLASH_BIT_ADDR, OP_NONE    }, -1 }, // 0xa0
  { "ajmp",  { OP_PAGE,       OP_NONE,      OP_NONE    },  5 }, // 0xa1
  { "mov",   { OP_C,          OP_BIT_ADDR,  OP_NONE    }, -1 }, // 0xa2
  { "inc",   { OP_DPTR,       OP_NONE,      OP_NONE    }, -1 }, // 0xa3
  { "mul",   { OP_AB,         OP_NONE,      OP_NONE    }, -1 }, // 0xa4
  { "???",   { OP_NONE,       OP_NONE,      OP_NONE    }, -1 }, // 0xa5
  { "mov",   { OP_AT_REG,     OP_IRAM_ADDR, OP_NONE    },  0 }, // 0xa6
  { "mov",   { OP_AT_REG,     OP_IRAM_ADDR, OP_NONE    },  1 }, // 0xa7
  { "mov",   { OP_REG,        OP_IRAM_ADDR, OP_NONE    },  0 }, // 0xa8
  { "mov",   { OP_REG,        OP_IRAM_ADDR, OP_NONE    },  1 }, // 0xa9
  { "mov",   { OP_REG,        OP_IRAM_ADDR, OP_NONE    },  2 }, // 0xaa
  { "mov",   { OP_REG,        OP_IRAM_ADDR, OP_NONE    },  3 }, // 0xab
  { "mov",   { OP_REG,        OP_IRAM_ADDR, OP_NONE    },  4 }, // 0xac
  { "mov",   { OP_REG,        OP_IRAM_ADDR, OP_NONE    },  5 }, // 0xad
  { "mov",   { OP_REG,        OP_IRAM_ADDR, OP_NONE    },  6 }, // 0xae
  { "mov",   { OP_REG,        OP_IRAM_ADDR, OP_NONE    },  7 }, // 0xaf
  { "anl",   { OP_C,     OP_SLASH_BIT_ADDR, OP_NONE    }, -1 }, // 0xb0
  { "acall", { OP_PAGE,       OP_NONE,      OP_NONE    },  5 }, // 0xb1
  { "cpl",   { OP_BIT_ADDR,   OP_NONE,      OP_NONE    }, -1 }, // 0xb2
  { "cpl",   { OP_C,          OP_NONE,      OP_NONE    }, -1 }, // 0xb3
  { "cjne",  { OP_A,          OP_DATA,      OP_RELADDR }, -1 }, // 0xb4
  { "cjne",  { OP_A,          OP_IRAM_ADDR, OP_RELADDR }, -1 }, // 0xb5
  { "cjne",  { OP_AT_REG,     OP_DATA,      OP_RELADDR },  0 }, // 0xb6
  { "cjne",  { OP_AT_REG,     OP_DATA,      OP_RELADDR },  1 }, // 0xb7
  { "cjne",  { OP_REG,        OP_DATA,      OP_RELADDR },  0 }, // 0xb8
  { "cjne",  { OP_REG,        OP_DATA,      OP_RELADDR },  1 }, // 0xb9
  { "cjne",  { OP_REG,        OP_DATA,      OP_RELADDR },  2 }, // 0xba
  { "cjne",  { OP_REG,        OP_DATA,      OP_RELADDR },  3 }, // 0xbb
  { "cjne",  { OP_REG,        OP_DATA,      OP_RELADDR },  4 }, // 0xbc
  { "cjne",  { OP_REG,        OP_DATA,      OP_RELADDR },  5 }, // 0xbd
  { "cjne",  { OP_REG,        OP_DATA,      OP_RELADDR },  6 }, // 0xbe
  { "cjne",  { OP_REG,        OP_DATA,      OP_RELADDR },  7 }, // 0xbf
  { "push",  { OP_IRAM_ADDR,  OP_NONE,      OP_NONE    }, -1 }, // 0xc0
  { "ajmp",  { OP_PAGE,       OP_NONE,      OP_NONE    },  6 }, // 0xc1
  { "clr",   { OP_BIT_ADDR,   OP_NONE,      OP_NONE    }, -1 }, // 0xc2
  { "clr",   { OP_C,          OP_NONE,      OP_NONE    }, -1 }, // 0xc3
  { "swap",  { OP_A,          OP_NONE,      OP_NONE    }, -1 }, // 0xc4
  { "xch",   { OP_A,          OP_IRAM_ADDR, OP_NONE    }, -1 }, // 0xc5
  { "xch",   { OP_A,          OP_AT_REG,    OP_NONE    },  0 }, // 0xc6
  { "xch",   { OP_A,          OP_AT_REG,    OP_NONE    },  1 }, // 0xc7
  { "xch",   { OP_A,          OP_REG,       OP_NONE    },  0 }, // 0xc8
  { "xch",   { OP_A,          OP_REG,       OP_NONE    },  1 }, // 0xc9
  { "xch",   { OP_A,          OP_REG,       OP_NONE    },  2 }, // 0xca
  { "xch",   { OP_A,          OP_REG,       OP_NONE    },  3 }, // 0xcb
  { "xch",   { OP_A,          OP_REG,       OP_NONE    },  4 }, // 0xcc
  { "xch",   { OP_A,          OP_REG,       OP_NONE    },  5 }, // 0xcd
  { "xch",   { OP_A,          OP_REG,       OP_NONE    },  6 }, // 0xce
  { "xch",   { OP_A,          OP_REG,       OP_NONE    },  7 }, // 0xcf
  { "pop",   { OP_IRAM_ADDR,  OP_NONE,      OP_NONE    }, -1 }, // 0xd0
  { "acall", { OP_PAGE,       OP_NONE,      OP_NONE    },  6 }, // 0xd1
  { "setb",  { OP_BIT_ADDR,   OP_NONE,      OP_NONE    }, -1 }, // 0xd2
  { "setb",  { OP_C,          OP_NONE,      OP_NONE    }, -1 }, // 0xd3
  { "da",    { OP_A,          OP_NONE,      OP_NONE    }, -1 }, // 0xd4
  { "djnz",  { OP_IRAM_ADDR,  OP_RELADDR,   OP_NONE    }, -1 }, // 0xd5
  { "xchd",  { OP_A,          OP_AT_REG,    OP_NONE    },  0 }, // 0xd6
  { "xchd",  { OP_A,          OP_AT_REG,    OP_NONE    },  1 }, // 0xd7
  { "djnz",  { OP_REG,        OP_RELADDR,   OP_NONE    },  0 }, // 0xd8
  { "djnz",  { OP_REG,        OP_RELADDR,   OP_NONE    },  1 }, // 0xd9
  { "djnz",  { OP_REG,        OP_RELADDR,   OP_NONE    },  2 }, // 0xda
  { "djnz",  { OP_REG,        OP_RELADDR,   OP_NONE    },  3 }, // 0xdb
  { "djnz",  { OP_REG,        OP_RELADDR,   OP_NONE    },  4 }, // 0xdc
  { "djnz",  { OP_REG,        OP_RELADDR,   OP_NONE    },  5 }, // 0xdd
  { "djnz",  { OP_REG,        OP_RELADDR,   OP_NONE    },  6 }, // 0xde
  { "djnz",  { OP_REG,        OP_RELADDR,   OP_NONE    },  7 }, // 0xdf
  { "movx",  { OP_A,          OP_AT_DPTR,   OP_NONE    }, -1 }, // 0xe0
  { "ajmp",  { OP_PAGE,       OP_NONE,      OP_NONE    },  7 }, // 0xe1
  { "movx",  { OP_A,          OP_AT_REG,    OP_NONE    },  0 }, // 0xe2
  { "movx",  { OP_A,          OP_AT_REG,    OP_NONE    },  1 }, // 0xe3
  { "clr",   { OP_A,          OP_NONE,      OP_NONE    }, -1 }, // 0xe4
  { "mov",   { OP_A,          OP_IRAM_ADDR, OP_NONE    }, -1 }, // 0xe5
  { "mov",   { OP_A,          OP_AT_REG,    OP_NONE    },  0 }, // 0xe6
  { "mov",   { OP_A,          OP_AT_REG,    OP_NONE    },  1 }, // 0xe7
  { "mov",   { OP_A,          OP_REG,       OP_NONE    },  0 }, // 0xe8
  { "mov",   { OP_A,          OP_REG,       OP_NONE    },  1 }, // 0xe9
  { "mov",   { OP_A,          OP_REG,       OP_NONE    },  2 }, // 0xea
  { "mov",   { OP_A,          OP_REG,       OP_NONE    },  3 }, // 0xeb
  { "mov",   { OP_A,          OP_REG,       OP_NONE    },  4 }, // 0xec
  { "mov",   { OP_A,          OP_REG,       OP_NONE    },  5 }, // 0xed
  { "mov",   { OP_A,          OP_REG,       OP_NONE    },  6 }, // 0xee
  { "mov",   { OP_A,          OP_REG,       OP_NONE    },  7 }, // 0xef
  { "movx",  { OP_AT_DPTR,    OP_A,         OP_NONE    }, -1 }, // 0xf0
  { "acall", { OP_PAGE,       OP_NONE,      OP_NONE    },  7 }, // 0xf1
  { "movx",  { OP_AT_REG,     OP_A,         OP_NONE    },  0 }, // 0xf2
  { "movx",  { OP_AT_REG,     OP_A,         OP_NONE    },  1 }, // 0xf3
  { "cpl",   { OP_A,          OP_NONE,      OP_NONE    }, -1 }, // 0xf4
  { "mov",   { OP_IRAM_ADDR,  OP_A,         OP_NONE    }, -1 }, // 0xf5
  { "mov",   { OP_AT_REG,     OP_A,         OP_NONE    },  0 }, // 0xf6
  { "mov",   { OP_AT_REG,     OP_A,         OP_NONE    },  1 }, // 0xf7
  { "mov",   { OP_REG,        OP_A,         OP_NONE    },  0 }, // 0xf8
  { "mov",   { OP_REG,        OP_A,         OP_NONE    },  1 }, // 0xf9
  { "mov",   { OP_REG,        OP_A,         OP_NONE    },  2 }, // 0xfa
  { "mov",   { OP_REG,        OP_A,         OP_NONE    },  3 }, // 0xfb
  { "mov",   { OP_REG,        OP_A,         OP_NONE    },  4 }, // 0xfc
  { "mov",   { OP_REG,        OP_A,         OP_NONE    },  5 }, // 0xfd
  { "mov",   { OP_REG,        OP_A,         OP_NONE    },  6 }, // 0xfe
  { "mov",   { OP_REG,        OP_A,         OP_NONE    },  7 }, // 0xff
};

